[colors]
bg = #cc000000
bg-alt = #000000
fg = #ffffff
fg-alt = #aea79f
accent = #e95420
urgent = #c01c28

[bar/bottom]
width = 100%:-60
height = 40
radius = 10

offset-x = 30
offset-y = 14

bottom = true
fixed-center = true

background = ${colors.bg}
foreground = ${colors.fg}

line-size = 0
border-size = 0

padding-left = 1
padding-right = 1

module-margin = 1

font-0 = AdwaitaMono Nerd Font:size=10;2

wm-restack = bspwm
override-redirect = true
enable-ipc = true

modules-left = bspwm
# modules-center = date
modules-right = network pulseaudio battery date

cursor-click = pointer
cursor-scroll = ns-resize

[module/bspwm]
type = internal/bspwm

pin-workspaces = false
inline-mode = true
enable-click = true
enable-scroll = false
reverse-scroll = false

format = <label-state>
format-padding = 0

ws-icon-0 = 1;
ws-icon-1 = 2;󰖟
ws-icon-2 = 3;
ws-icon-3 = 4;󱔘
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;
ws-icon-9 = 10;
ws-icon-default = 

label-focused =  %icon% 
label-focused-background = ${colors.accent}
label-focused-foreground = ${colors.fg}
label-focused-padding = 1

label-occupied =  %icon% 
label-occupied-foreground = ${colors.fg}
label-occupied-background = ${colors.bg}
label-occupied-padding = 1

label-empty =  %icon% 
label-empty-foreground = ${colors.fg-alt}
label-empty-background = ${colors.bg}
label-empty-padding = 1

label-urgent =  %icon% 
label-urgent-background = ${colors.urgent}
label-urgent-foreground = ${colors.fg}
label-urgent-padding = 1

label-separator = " "
label-separator-foreground = ${colors.bg}

[module/date]
type = internal/date
interval = 1
date = %a, %b %d
time = %H:%M
label = 󰃭 %date% |  %time%

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
label-volume =  %percentage%%
label-muted =  mute

[module/network]
type = internal/network
interface-type = wireless
interval = 3
format-connected = <label-connected>
# 
label-connected =  %essid%
format-disconnected = <label-disconnected>
label-disconnected = 󰤮 down

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
poll-interval = 10
format-charging = <label-charging>
format-discharging = <label-discharging>
label-charging =  %percentage%%
label-discharging =  %percentage%%
label-full =  100%%